baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Mistrzostwa Polski Agility 2023'
  metaDescription = "Mistrzostwa Polski Agility 2023"


[languages]
  [languages.en]
    contentDir = 'content/english'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 1
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
  [languages.pl]
    contentDir = 'content/pl'
    disabled = false
    languageCode = 'pl-PL'
    languageDirection = 'ltr'
    languageName = 'Polski'
    title = 'Project Documentation'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

[taxonomies]
  category= "theme"
  scene = "scenes"
