baseURL = 'https://agilitypoland.dog/'
languageCode = 'pl-pl'
defaultContentLanguage = 'pl'


[params]
  title = 'Mistrzostwa Polski Agility 2023'
  metaDescription = "Mistrzostwa Polski Agility 2023"

[permalinks]
  news = "/:slug/"

[languages]
  [languages.en]
    contentDir = 'content/english'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 1
    [languages.en.permalinks]
      [languages.en.permalinks.page]
        news = '/:slug/'
  [languages.pl]
    contentDir = 'content/pl'
    disabled = false
    languageCode = 'pl-PL'
    languageDirection = 'ltr'
    languageName = 'Polski'
    title = 'Project Documentation'
    weight = 2
    [languages.pl.permalinks]
      [languages.pl.permalinks.page]
        news = '/:slug/'

[taxonomies]
  category= "theme"
  scene = "scenes"
