baseURL = 'https://agilitypoland.dog'
languageCode = 'pl-pl'
defaultContentLanguage = 'pl'

[params]
  title = 'Mistrzostwa Polski Agility 2023'
  metaDescription = "Mistrzostwa Polski Agility 2023"

[markup.goldmark.renderer]
  unsafe= true

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    [languages.en.permalinks]
      [languages.en.permalinks.page]
        news = '/:slug/'
        sponsors = '/:slug/'
  [languages.pl]
    contentDir = 'content/pl'
    disabled = false
    languageCode = 'pl-PL'
    languageDirection = 'ltr'
    languageName = 'Polski'
    weight = 2
    [languages.pl.permalinks]
      [languages.pl.permalinks.page]
        news = '/:slug/'
        sponsors = '/sponsors/:slug/'
