# using git as backend store
backend:
  name: git-gateway
  local_backend: true
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: false
locale: 'en'

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [ en, pl ]
  default_locale: en


# collections configuration
collections:
  - name: "sections"
    label: "Global settings"
    i18n:
      structure: single_file
      locales: [ en, pl ]
    files:
      - file: "data/settings.yml"
        i18n: true
        label: "Settings"
        name: "settings"
        fields: [
          { label: "Logo", name: "logo", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "Footer Logo", name: "footer_logo", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "FB Group URL", name: "fbgroup", widget: "string" , i18n: true },
          { label: "FB Group Title", name: "fbgroup_title", widget: "string" , i18n: true },
          { label: "Contact Email", name: "email", widget: "string" , i18n: true },
          { label: "Menu Items", name: "menu", widget: "list", i18n: true, fields: [
            { label: "Link Title", name: "title", widget: string , i18n: true },
            { label: "URL", name: "url", widget: string, i18n: true },
            { label: "Submenu Items", name: "submenu", widget: "list", i18n: true, fields: [
              { label: "Link Title", name: "title", widget: string , i18n: true },
              { label: "URL", name: "url", widget: string, i18n: true }
            ] }
          ] },
          { label: "Social Links", name: "socials", widget: "list", i18n: true, fields: [
            { label: "Title", name: "title", widget: string , i18n: true },
            { label: "Icon", name: "icon", widget: string , i18n: true },
            { label: "URL", name: "url", widget: string, i18n: true }
          ] }
        ]
      - file: "data/home.yml"
        i18n: true
        label: "Home"
        name: "home"
        fields: [
          { label: "Title", name: "title", widget: string, i18n: true },
          { label: "Slogan", name: "slogan", widget: string, i18n: true },
          { label: "Description", name: "shortDescription", widget: "text", i18n: true },
          { label: "Header Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "Register", name: "register", widget: string, i18n: true },
          { label: "Copyright", name: "copyright", widget: string, i18n: true },
          { label: "Body", name: "body", widget: "markdown", i18n: true },
        ]
  - name: "news"
    label: "Pages (en)"
    folder: "content/english/news"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Slug", name: "slug", widget: "string" },
        { label: "Background Image", name: "image", widget: "image" },
        { label: ".", name: "body", widget: "markdown" },
      ]
  - name: "news-pl"
    label: "Pages (pl)"
    folder: "content/pl/news"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Slug", name: "slug", widget: "string" },
        { label: "Background Image", name: "image", widget: "image" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
