# using git as backend store
backend:
  name: git-gateway
  local_backend: true
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: false
locale: 'en'

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [ en, pl ]
  default_locale: pl


# collections configuration
collections:
  - name: "sections"
    label: "Global settings"
    i18n:
      structure: single_file 
      locales: [ en, pl ]
    files:
      - file: "data/settings.yml"
        i18n: true
        label: "Settings"
        name: "settings"
        fields: [
          { label: "Website Title", name: "title", widget: "string" , i18n: true },
          { label: "Website Description", name: "description", widget: "string" , i18n: true },
          { label: "Logo", name: "logo", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "Logo Width", name: "logo_width", widget: "string" , i18n: true },
          { label: "Social Media image", name: "social_image", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true, required: false },
          { label: "Favicon", name: "favicon", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "Footer Logo", name: "footer_logo", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "FB Group URL", name: "fbgroup", widget: "string" , i18n: true },
          { label: "FB Group Title", name: "fbgroup_title", widget: "string" , i18n: true },
          { label: "Contact Email", name: "email", widget: "string" , i18n: true },
          { label: "Menu Items", name: "menu", widget: "list", i18n: true, fields: [
            { label: "Link Title", name: "title", widget: string , i18n: true },
            { label: "URL", name: "url", widget: string, i18n: true },
            { label: "Open in new window", name: "newwindow", widget: "boolean", i18n: true, required: false },
            { label: "Submenu Items", name: "submenu", widget: "list", i18n: true, fields: [
              { label: "Link Title", name: "title", widget: string , i18n: true },
              { label: "URL", name: "url", widget: string, i18n: true },
              { label: "Open in new window", name: "newwindow", widget: "boolean", i18n: true, required: false }
            ] }
          ] },
          { label: "Social Links", name: "socials", widget: "list", i18n: true, fields: [
            { label: "Title", name: "title", widget: string , i18n: true },
            { label: "Icon", name: "icon", widget: string , i18n: true },
            { label: "URL", name: "url", widget: string, i18n: true }
          ] },
          { label: "Footer menu", name: "footer_menu", widget: "list", i18n: true, fields: [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "Items", name: "items", widget: "list", i18n: true, fields: [
              { label: "Title", name: "title", widget: string , i18n: true },
              { label: "URL", name: "url", widget: string, i18n: true },
              { label: "Open in new window", name: "new_window", widget: "boolean" , i18n: true, required: false }
            ] }
          ] }
        ]
      - file: "data/home.yml"
        i18n: true
        label: "Home"
        name: "home"
        fields: [
          { label: "Title", name: "title", widget: string, i18n: true },
          { label: "Header Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "Body", name: "body", widget: "markdown", i18n: true },
        ]
  - name: "news"
    label: "Pages (en)"
    folder: "content/en/news"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Slug", name: "slug", widget: "string" },
        { label: "Slug (pl)", name: "slug_lng", widget: "string" },
        { label: "Background Image", name: "image", widget: "image", required: false },
        { label: ".", name: "body", widget: "markdown", required: false },
        { label: "HTML Body", name: "html_body", widget: "markdown", required: false }
      ]
  - name: "news-pl"
    label: "Pages (pl)"
    folder: "content/pl/news"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Slug", name: "slug", widget: "string" },
        { label: "Slug (en)", name: "slug_lng", widget: "string" },
        { label: "Background Image", name: "image", widget: "image", required: false },
        { label: "Body", name: "body", widget: "markdown" },
        { label: "HTML Body", name: "html_body", widget: "text" }
      ]
  - name: "sponsors"
    label: "Sponsors"
    folder: "content/pl/sponsors"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Slug", name: "slug", widget: "string" },
        { label: "Logo", name: "logo", widget: "image", required: false },
        { label: "Body", name: "body", widget: "markdown" },
        { label: "Facebook", name: "facebook", widget: "string", required: false },
        { label: "Instagram", name: "instagram", widget: "string", required: false },
        { label: "Website Title", name: "website", widget: "string", required: false },
        { label: "Website URL", name: "website_url", widget: "string", required: false },
        { label: "Gallery", name: "gallery", widget: "list", i18n: true, fields: [
          { label: "Image", name: "image", widget: "text" }
        ] }
      ]
